### ISSUE TITLE
Calling undefined chef-vault method with chef-vault 1.3.1

### ISSUE THREAD

**Issue by matomesc** [onbeep-cookbooks/ssl-vault#10]
I froze `chef-vault` to 1.3.0 to work around this for now.

See the following stack trace:
```
NoMethodError: undefined method `vault?' for ChefVault::Item:Class
/var/chef/cache/cookbooks/chef-vault/libraries/helpers.rb:36:in `chef_vault_item'
/var/chef/cache/cookbooks/ssl-vault/recipes/certificate_file.rb:21:in `block in from_file'
/var/chef/cache/cookbooks/ssl-vault/recipes/certificate_file.rb:16:in `each'
/var/chef/cache/cookbooks/ssl-vault/recipes/certificate_file.rb:16:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/cookbook_version.rb:228:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/run_context.rb:174:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/run_context.rb:143:in `block in include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/run_context.rb:142:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/run_context.rb:142:in `include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/ssl-vault/recipes/default.rb:15:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/cookbook_version.rb:228:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/run_context.rb:174:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/run_context.rb:97:in `load'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/policy_builder/expand_node_object.rb:87:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/client.rb:486:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/client.rb:266:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/application.rb:258:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/application.rb:224:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/application.rb:212:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/application/client.rb:392:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/application/client.rb:382:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.3/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
```

**Comment by mjuarez** [comment]
Pretty sure this issue is related and will be solved by: https://github.com/orion-cookbooks/ssl-vault/pull/9
